@userAccessToken = Bearer {{createUser.res.body.accesstoken}}

# @name createUser
POST http://localhost:4000/register
Content-Type: application/json

{
  "email": "murat.hey@gmail.com",
  "password": "test"
}
###

# @name login
POST http://localhost:4000/login
Content-Type: application/json

{
  "email": "murat.hey@gmail.com",
  "password": "test"
}
###

### you may need to past the access to ken you get from login
# @name testProtectedRoute
POST http://localhost:4000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTU3MzkxMTUyNSwiZXhwIjoxNTczOTEyNDI1fQ.1rT0M-IoNugrXIiDjOnq1zlagHJmAw7YXUBkZF2CUnI

{
  "email": "murat.hey@gmail.com",
  "password": "test"
}
###

# @name testRefresh
POST http://localhost:4000/refresh_token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTU3MzkxMTUyNSwiZXhwIjoxNTczOTEyNDI1fQ.1rT0M-IoNugrXIiDjOnq1zlagHJmAw7YXUBkZF2CUnI

{
  "email": "murat.hey@gmail.com",
  "password": "test"
}
###

# @name logout
POST http://localhost:4000/logout

###
